package service

import (
	_ "go.dtapp.net/library/service/dingdanxia"
	_ "go.dtapp.net/library/service/dingtalk"
	_ "go.dtapp.net/library/service/eastiot"
	_ "go.dtapp.net/library/service/ejiaofei"
	_ "go.dtapp.net/library/service/feishu"
	_ "go.dtapp.net/library/service/ip"
	_ "go.dtapp.net/library/service/jd"
	_ "go.dtapp.net/library/service/jobs"
	_ "go.dtapp.net/library/service/kashangwl"
	_ "go.dtapp.net/library/service/leshuazf"
	_ "go.dtapp.net/library/service/meituan"
	_ "go.dtapp.net/library/service/pinduoduo"
	_ "go.dtapp.net/library/service/pintoto"
	_ "go.dtapp.net/library/service/sendcloud"
	_ "go.dtapp.net/library/service/taobao"
	_ "go.dtapp.net/library/service/tianyancha"
	_ "go.dtapp.net/library/service/wechatminiprogram"
	_ "go.dtapp.net/library/service/wechatoffice"
	_ "go.dtapp.net/library/service/wechatopen"
	_ "go.dtapp.net/library/service/wechatpayapiv2"
	_ "go.dtapp.net/library/service/wechatpayapiv3"
	_ "go.dtapp.net/library/service/wechatqy"
	_ "go.dtapp.net/library/service/wechatunion"
	_ "go.dtapp.net/library/service/wikeyun"
)
